name: flank-slack-bot

description: Send slack notifications about flank releases
author: Flank

branding:
  icon: file-plus
  color: blue

runs:
  using: 'docker'
  image: './flank-actions/Dockerfile'

inputs:
  xoxctoken:
    description: A slack token that gives permission to act as a user.
    required: true
  message: 
    description: The message to send
    required: true
  channel:
    description: Channel to send to
    required: true
  cookie: 
    description: Required cookie for auth
    required: true
